import { ClinicalCase } from '../types';

export const CLINICAL_CASES: ClinicalCase[] = [
  {
    id: 'stemi-anterior',
    title: 'Acute Anterior STEMI (Proximal LAD Occlusion)',
    category: 'Coronary',
    difficulty: 'Fellow',
    brief: '58-year-old male presenting with 90 minutes of crushing substernal chest pressure, diaphoresis, and radiation to the left arm.',
    patient: {
      id: 'pt-001',
      name: 'Arthur P.',
      age: 58,
      gender: 'male',
      chiefComplaint: 'Severe substernal chest crushing pain (9/10), cold diaphoresis',
      historyOfPresentIllness: 'Sudden onset while walking his dog. Pain radiates to left jaw and shoulder. Refractory to sublingual nitroglycerin administered by EMS.',
      pastMedicalHistory: ['Hypertension', 'Dyslipidemia', '30 pack-year smoking history'],
      vitals: {
        heartRate: 98,
        sbp: 142,
        dbp: 88,
        respiratoryRate: 22,
        spo2: 95,
        temperature: 36.8,
      },
      labs: {
        troponin: 1.45,
        troponinBaseline: 0.01,
        bnp: 180,
        creatinine: 1.1,
        egfr: 78,
        potassium: 4.2,
        sodium: 139,
        hemoglobin: 14.5,
        ldl: 162,
        hba1c: 6.8,
      },
      ecgSummary: {
        rhythm: 'Sinus Tachycardia',
        prInterval: 155,
        qrsDuration: 96,
        qtc: 440,
        axis: '+30° (Normal)',
        stSegment: '4mm ST-elevation in V1-V4 with reciprocal ST-depression in II, III, aVF',
        findings: 'Hyperacute T-waves transitioning to tombstoning ST elevation in anteroseptal leads.',
      },
      echoSummary: {
        lvef: 38,
        wallMotionAbnormality: 'Severe hypokinesis to akinesis of anterior wall and apex',
        valvularFindings: 'Trace mitral regurgitation, no aortic stenosis',
        lvedd: 54,
        eOverEPrime: 13.5,
        pasP: 34,
      },
      currentMedications: ['Amlodipine 5mg QD', 'Atorvastatin 20mg QD'],
    },
    expectedDiagnosis: 'Acute ST-Elevation Myocardial Infarction (Anteroseptal/Apical) due to acute Thrombotic Occlusion of the Proximal Left Anterior Descending (LAD) Coronary Artery.',
    pearl: 'Door-to-balloon time target is <90 minutes (<120 min if transfer). Immediate dual antiplatelet therapy (Aspirin 300mg + Ticagrelor 180mg or Prasugrel 60mg) + unfractionated heparin bolus.',
  },
  {
    id: 'stemi-inferior',
    title: 'Acute Inferior STEMI (Dominant RCA Occlusion)',
    category: 'Coronary',
    difficulty: 'Fellow',
    brief: '61-year-old male presenting with 2 hours of crushing epigastric and retrosternal heaviness, nausea, cold sweats, and sinus bradycardia.',
    patient: {
      id: 'pt-001b',
      name: 'Marcus D.',
      age: 61,
      gender: 'male',
      chiefComplaint: 'Crushing epigastric pressure, nausea, lightheadedness and diaphoresis',
      historyOfPresentIllness: 'Sudden onset dull burning retrosternal/epigastric ache radiating to jaw and back. Associated with acute nausea and sinus bradycardia.',
      pastMedicalHistory: ['Hypertension', 'Dyslipidemia', 'Type 2 Diabetes'],
      vitals: {
        heartRate: 52,
        sbp: 104,
        dbp: 66,
        respiratoryRate: 18,
        spo2: 96,
        temperature: 36.6,
      },
      labs: {
        troponin: 1.82,
        troponinBaseline: 0.01,
        bnp: 140,
        creatinine: 1.05,
        egfr: 76,
        potassium: 4.1,
        sodium: 138,
        hemoglobin: 14.1,
        ldl: 148,
        hba1c: 7.1,
      },
      ecgSummary: {
        rhythm: 'Sinus Bradycardia with 1st degree AV block',
        prInterval: 220,
        qrsDuration: 94,
        qtc: 435,
        axis: '+85° (Vertical)',
        stSegment: '3.5mm ST-elevation in leads II, III, aVF (lead III > lead II) with reciprocal ST-depression in I and aVL',
        findings: 'Acute transmural inferior myocardial infarction. Right-sided V4R shows 1mm ST-elevation concerning for proximal RCA/RV involvement.',
      },
      echoSummary: {
        lvef: 46,
        wallMotionAbnormality: 'Akinetic to severely hypokinetic basal and mid inferior wall and posterior septum',
        valvularFindings: 'Mild-moderate ischemic mitral regurgitation secondary to posterior papillary muscle hypoperfusion',
        lvedd: 52,
        eOverEPrime: 12.0,
        pasP: 30,
      },
      currentMedications: ['Metformin 1000mg BID', 'Ramipril 5mg QD'],
    },
    expectedDiagnosis: 'Acute ST-Elevation Myocardial Infarction (Inferior Wall) due to acute Thrombotic Occlusion of the Dominant Right Coronary Artery (RCA).',
    pearl: 'Avoid nitrates and diuretics in RV/inferior infarction as preload reduction can precipitate profound hypotension. Immediate D2B <90m primary PCI.',
  },
  {
    id: 'hfref-decompensation',
    title: 'Decompensated HFrEF (EF 24%) with Volume Overload',
    category: 'Heart Failure',
    difficulty: 'Resident',
    brief: '66-year-old female with known non-ischemic cardiomyopathy presenting with orthopnea, bendopnea, and 3+ bilateral lower extremity edema.',
    patient: {
      id: 'pt-002',
      name: 'Elena R.',
      age: 66,
      gender: 'female',
      chiefComplaint: 'Worsening shortness of breath on minimal exertion, 3-pillow orthopnea',
      historyOfPresentIllness: 'Progressive exertional dyspnea over 10 days, accompanied by a 4.5 kg weight gain and dry nocturnal cough.',
      pastMedicalHistory: ['Non-ischemic dilated cardiomyopathy', 'Type 2 Diabetes Mellitus', 'Chronic Kidney Disease Stage 3a'],
      vitals: {
        heartRate: 84,
        sbp: 114,
        dbp: 72,
        respiratoryRate: 20,
        spo2: 92,
        temperature: 36.7,
      },
      labs: {
        troponin: 0.04,
        bnp: 1450,
        creatinine: 1.55,
        egfr: 41,
        potassium: 4.6,
        sodium: 134,
        hemoglobin: 11.2,
        ldl: 85,
        hba1c: 7.4,
      },
      ecgSummary: {
        rhythm: 'Normal Sinus Rhythm with frequent PACs',
        prInterval: 180,
        qrsDuration: 136,
        qtc: 458,
        axis: '-35° (Left Axis Deviation)',
        stSegment: 'Non-specific ST-T wave changes with secondary repolarization abnormality',
        findings: 'Left Bundle Branch Block (LBBB) morphology with QRS width 136 ms.',
      },
      echoSummary: {
        lvef: 24,
        wallMotionAbnormality: 'Diffuse global hypokinesis with intraventricular dyssynchrony',
        valvularFindings: 'Moderate functional mitral regurgitation secondary to annular dilation',
        lvedd: 66,
        eOverEPrime: 18.2,
        pasP: 48,
      },
      currentMedications: ['Furosemide 40mg BID', 'Metoprolol Tartrate 25mg BID (sub-optimal)'],
    },
    expectedDiagnosis: 'Acute Decompensated Heart Failure (Wet-Warm Profile) in the setting of Severe HFrEF with LBBB and incomplete 4-pillar GDMT.',
    pearl: 'Switch to Metoprolol Succinate or Carvedilol once euvolemic. Initiate SGLT2 inhibitor (Dapagliflozin/Empagliflozin 10mg) immediately as it promotes decongestion without lowering BP. Check eligibility for CRT-D (LBBB, QRS >130ms, EF <35%).',
  },
  {
    id: 'torsades-long-qt',
    title: 'Drug-Induced Long QT & Intermittent Torsades de Pointes',
    category: 'Arrhythmia',
    difficulty: 'Fellow',
    brief: '42-year-old woman treated with azithromycin and ondansetron for gastroenteritis presenting with recurrent syncope and palpitations.',
    patient: {
      id: 'pt-003',
      name: 'Sophia K.',
      age: 42,
      gender: 'female',
      chiefComplaint: 'Sudden collapse with spontaneous recovery, pre-syncopal lightheadedness',
      historyOfPresentIllness: 'Had 3 episodes of sudden loss of consciousness within 12 hours. Paramedics documented self-terminating polymorphic ventricular tachycardia.',
      pastMedicalHistory: ['Depression (on Citalopram)', 'Recent atypical pneumonia'],
      vitals: {
        heartRate: 54,
        sbp: 108,
        dbp: 68,
        respiratoryRate: 16,
        spo2: 98,
        temperature: 36.9,
      },
      labs: {
        troponin: 0.02,
        bnp: 65,
        creatinine: 0.85,
        egfr: 96,
        potassium: 3.1, // Hypokalemia!
        sodium: 137,
        hemoglobin: 13.0,
        ldl: 110,
        hba1c: 5.4,
      },
      ecgSummary: {
        rhythm: 'Sinus Bradycardia with giant bifid T-U fusion waves',
        prInterval: 170,
        qrsDuration: 92,
        qtc: 540,
        axis: '+45°',
        stSegment: 'Marked QT interval prolongation (>540 ms)',
        findings: 'Dangerous R-on-T premature ventricular complexes initiating twisting QRS peaks.',
      },
      echoSummary: {
        lvef: 60,
        wallMotionAbnormality: 'Normal biventricular systolic function',
        valvularFindings: 'Structurally normal valves',
        lvedd: 46,
        eOverEPrime: 7.2,
        pasP: 22,
      },
      currentMedications: ['Citalopram 40mg QD', 'Azithromycin 500mg QD', 'Ondansetron 8mg PRN'],
    },
    expectedDiagnosis: 'Acquired Long QT Syndrome (LQTS) with Torsades de Pointes triggered by synergistic drug-induced hERG K+ channel blockade and hypokalemia.',
    pearl: 'Immediate IV Magnesium Sulfate (2g IV over 1-2 min). Aggressively replete Potassium to >4.5 mEq/L. Stop all QT-prolonging agents. Temporary transvenous pacing or Isoproterenol if bradycardia-dependent.',
  },
  {
    id: 'severe-as-tavr',
    title: 'Severe Symptomatic Aortic Stenosis (TAVR Evaluation)',
    category: 'Valvular',
    difficulty: 'Resident',
    brief: '79-year-old male with exertional angina and near-syncope during stair climbing.',
    patient: {
      id: 'pt-004',
      name: 'Robert V.',
      age: 79,
      gender: 'male',
      chiefComplaint: 'Exertional dyspnea, lightheadedness, and crescendo-decrescendo systolic murmur',
      historyOfPresentIllness: 'Progressive limitation over 6 months; now unable to climb one flight of stairs without severe dizziness.',
      pastMedicalHistory: ['Hypertension', 'Peripheral Artery Disease'],
      vitals: {
        heartRate: 70,
        sbp: 130,
        dbp: 82,
        respiratoryRate: 18,
        spo2: 96,
        temperature: 36.6,
      },
      labs: {
        troponin: 0.03,
        bnp: 380,
        creatinine: 1.3,
        egfr: 52,
        potassium: 4.4,
        sodium: 140,
        hemoglobin: 12.8,
        ldl: 92,
        hba1c: 5.9,
      },
      ecgSummary: {
        rhythm: 'Normal Sinus Rhythm',
        prInterval: 190,
        qrsDuration: 104,
        qtc: 432,
        axis: '-15°',
        stSegment: 'ST depression and asymmetric T-wave inversion in I, aVL, V5-V6 (LV Strain Pattern)',
        findings: 'Sokolow-Lyon voltage criteria positive for Left Ventricular Hypertrophy (S in V1 + R in V5 = 42 mm).',
      },
      echoSummary: {
        lvef: 52,
        wallMotionAbnormality: 'Concentric LV hypertrophy with preserved ejection fraction',
        valvularFindings: 'Calcified trileaflet aortic valve. Aortic Valve Area (AVA) 0.72 cm² (index 0.38 cm²/m²), Mean Gradient 46 mmHg, Peak Jet Velocity 4.3 m/s.',
        lvedd: 48,
        eOverEPrime: 16.0,
        pasP: 38,
      },
      currentMedications: ['Amlodipine 5mg QD', 'Atorvastatin 40mg QD'],
    },
    expectedDiagnosis: 'Severe High-Gradient Symptomatic Aortic Stenosis (Stage D1) with classic triad symptom (angina, syncope, dyspnea).',
    pearl: 'Class I indication for urgent Aortic Valve Replacement (TAVR vs SAVR per Heart Team consensus). Avoid high-dose vasodilators (e.g. nitrates) as they can precipitate profound hypotension.',
  },
  {
    id: 'pericarditis-vs-stemi',
    title: 'Acute Viral Pericarditis vs Atypical ACS',
    category: 'Emergency',
    difficulty: 'Student',
    brief: '29-year-old medical student with sharp, pleuritic retrosternal chest pain relieved by sitting forward, following a flu-like illness.',
    patient: {
      id: 'pt-005',
      name: 'Lucas M.',
      age: 29,
      gender: 'male',
      chiefComplaint: 'Sharp stabbing chest pain worsened by lying flat and deep inspiration',
      historyOfPresentIllness: 'Pain started 24 hours ago. Friction rub heard on left sternal border. Pain radiates to the bilateral trapezius ridges.',
      pastMedicalHistory: ['Viral upper respiratory infection 1 week ago'],
      vitals: {
        heartRate: 88,
        sbp: 122,
        dbp: 76,
        respiratoryRate: 16,
        spo2: 99,
        temperature: 37.8,
      },
      labs: {
        troponin: 0.015,
        bnp: 45,
        creatinine: 0.9,
        egfr: 105,
        potassium: 4.1,
        sodium: 141,
        hemoglobin: 15.2,
        ldl: 95,
        hba1c: 5.1,
      },
      ecgSummary: {
        rhythm: 'Normal Sinus Rhythm',
        prInterval: 148,
        qrsDuration: 84,
        qtc: 410,
        axis: '+50°',
        stSegment: 'Widespread concave ST-elevation in almost all leads (I, II, aVF, V2-V6) with reciprocal ST-depression only in aVR and V1',
        findings: 'PR-segment depression in lead II and PR-segment elevation in lead aVR (classic Spodick sign).',
      },
      echoSummary: {
        lvef: 62,
        wallMotionAbnormality: 'Normal wall motion throughout, no regional wall abnormalities',
        valvularFindings: 'Normal valves. Trivial circumferential pericardial effusion (3mm), no tamponade physiology.',
        lvedd: 47,
        eOverEPrime: 6.8,
        pasP: 20,
      },
      currentMedications: ['Acetaminophen 500mg PRN'],
    },
    expectedDiagnosis: 'Acute Viral Myopericarditis / Pericarditis with pathognomonic PR depression and diffuse concave ST elevations.',
    pearl: 'First-line therapy is High-Dose Ibuprofen (600-800mg TID) or Aspirin + Colchicine (0.5mg BID or 0.5mg QD if <70kg) for 3 months to prevent recurrences. Exercise restriction until symptom resolution.',
  }
];
